#ifndef INCLUDE_GUARD
#define INCLUDE_GUARD

#define PROJECT_NAME "oberon0c"
#define PROJECT_VERSION  "0.0.1"
#define PROJECT_VER_MAJOR "0"
#define PROJECT_VER_MINOR "0"
#define PTOJECT_VER_PATCH "1"

#endif //INCLUDE_GUARD